#!/usr/bin/env python3
# coding: utf-8

##
# Interface with Mu-Land app
##
from pathlib import Path
import os, tempfile, subprocess
import csv

class MulandException(Exception):
    pass

class ModelNotFound(MulandException):
    pass

class DependencyError(MulandException):
    pass

class MulandRunError(MulandException):
    pass

class Muland:
    '''Access Muland Application'''

    muland_binary = 'bin/muland'
    model_folder = 'model'
    work_folder = 'work'

    input_files = ['agents', 'agents_zones', 'bids_adjustments',
    'bids_functions', 'demand', 'demand_exogenous_cutoff',
    'real_estates_zones', 'rent_adjustments', 'rent_functions',
    'subsidies', 'supply', 'zones']

    output_files = ['bids', 'bh', 'location', 'location_probability',
    'rents']

    # Check if muland binary, model folder and work folder are in place
    if not os.access(work_folder, os.R_OK & os.W_OK):
        if os.access(work_folder, os.F_OK):
            raise DependencyError('Could not access work folder.')
        os.mkdir(work_folder)

    if not os.access(muland_binary, os.X_OK):
        raise DependencyError('Could not find muland binary.')

    if not os.access(model_folder, os.R_OK):
        raise DependencyError('Could not access model folder.')

    def __init__(self, model):
        '''Initialize Muland'''
        # Check if model exists
        model_folder = self.model_folder
        for file in self.input_files:
            filename = str(Path(model_folder, model, file + '.csv'))
            accessible = os.access(filename, os.R_OK)
            if not accessible:
                raise ModelNotFound('Specified model was not found.')

        # Set instance attributes
        self.model_dir = str(Path(model_folder, model))
        self.output_data = {}

    def __getattr__(self, name):
        '''Interface to output_data keys'''
        try:
            return self.output_data[name]
        except KeyError:
            pass
        raise AttributeError('No attribute or output data named \'%s\'' % name)

    def _populate_working_dir(self, working_dir):
        '''Prepares data for Muland reading'''
        # Create input and output directories
        os.mkdir(str(Path(working_dir, 'input')))
        os.mkdir(str(Path(working_dir, 'output')))

        # Populate input directory
        model_folder = self.model_folder
        for file in self.input_files:
            model_file_path = str(Path(self.model_dir, file + '.csv').resolve())
            work_file_path = str(Path(working_dir, 'input', file + '.csv'))
            os.symlink(model_file_path, work_file_path)

    def _run_muland(self, working_dir, timeout=2):
        '''Run Muland on working dir'''
        with subprocess.Popen([self.muland_binary, working_dir],
                              stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE) as process:
            try:
                stdout, stderr = process.communicate(None, timeout=timeout)
                if stdout.find(b'Algorithm ended sucessfully') is -1:
                    raise MulandRunError('Mu-Land finished without success message')
            except subprocess.TimeoutExpired:
                process.kill()
                stdout, stderr = process.communicate()
                raise MulandRunError('Mu-Land proccess timeout.')
            except:
                process.kill()
                process.wait()
                raise MulandRunError('Unknown error running Mu-Land')

    def _collect_data(self, working_dir):
        '''Collects data generated by Muland'''
        for name in self.output_files:
            output_data = []
            fullname = str(Path(working_dir, 'output', name + '.csv'))
            with open(fullname) as file:
                next(file)
                reader = csv.reader(file, delimiter=';',
                                    quoting=csv.QUOTE_NONNUMERIC)
                for row in reader:
                    output_data.append(tuple(row))
            self.output_data[name] = output_data

    def run(self):
        '''Runs Muland'''
        # Create/destroy data directory
        with tempfile.TemporaryDirectory(dir = self.work_folder) as working_dir:
            # Prepare directory
            self._populate_working_dir(working_dir)

            # Run Muland
            self._run_muland(working_dir)

            # Collect data
            self._collect_data(working_dir)


##
# Interface with web server
##
import bottle
import re
import json

class MulandWeb:
    _model_re = re.compile('[a-z]')

    def __init__(self):
        self.app = bottle.Bottle()
        self.app.post('/<model>', callback=self.post_handler)
        self.app.get('/<model>', callback=self.post_handler)

    def __getattr__(self, name):
        '''Fallback to bottle app attributes'''
        return getattr(self.app, name)

    def post_handler(self, model):
        '''Handles POST requests to server'''
        if self._model_re.match(model) is None:
            raise bottle.HTTPError(404)

        try:
            mu = Muland(model)
        except ModelNotFound:
            raise bottle.HTTPError(404)

        try:
            mu.run()
        except MulandRunError as e:
            raise HTTPError(500, exception=e)

        bottle.response.headers['Content-Type'] = 'application/json'
        return json.dumps(mu.output_data)

app = application = MulandWeb()

if __name__ == '__main__':
    app.run(host = '', port = 8000)
